### PR TITLE
Navigator: Enhancements, fixes and macOS support

### PR DESCRIPTION
**Pull request by ghost**
- Fixed the totally broken file path detection. It wasn't resolving the
current path when files were opened with relative paths (such as "mpv
*.mkv" in a folder). So I rewrote everything to check for an absolute
path, and if not absolute then we prepend mpv's current working dir.
- Made the path detection resolve relative paths ("/foo/bar/../bar/"
becomes "/foo/bar/").
- Added final failsafe so that if the path detection came up with a
folder that doesn't actually exist, we fall back to starting the
navigation from mpv's current working dir instead.
- Rewrote the "isfolder" check in a more efficient, cross-platform way
so that it works on both Linux and macOS.
- Rewrote the folder scanner. Instead of wastefully using the overkill
"find" utility (along with non-compatible flags that don't work on
macOS), we now use "basename" instead and simply pass it a glob of all
files in the folder. It returns the basenames (filename without path)
for all files. That utility exists on both Linux and macOS, which means
that the script is now supported on macOS.
- Added a new function which clears the OSD, removes keybindings, and
restores the font size to normal. And made all "reset/close/cancel"
functions and timers use that instead.
- Fixed the broken "safe path" generator. It was replacing all sequences
of all kinds of whitespace with a single "\ " (a backslash and regular
space. That meant that it didn't support folders with non-space
whitespaces or more than a single space in a row. The new code solves
that by properly escaping every whitespace character one by one.
- Added useless macOS system paths to the default ignore list.
- Enhanced keybinding of the main key so that you can choose it in the
"settings" and can even set it to "nil" to allow you to bind it via
input.conf instead.
- Made it possible to rebind the "favorites" key via "settings".
- Simplified favorites configuration (there is no need to number keys).
- Added setting to choose how many OSD items to display per screen.
- Added automatic font size switching, so that you can use a smaller
font to see lots of files while the navigator is open and then return to
your normal OSD font size afterwards.
- Replaced all tabs with two spaces, because oh my god stop mixing tabs
in half the file and two spaces in the other half! ;-)

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the file navigator. I did have to fix a ton of things, but now it's working perfectly. Of course I want to contribute the code back to you as thanks, and to help others! 🍰 

By the way, I saw that you starred my mpv-tools repo. Well, I think you're going to love this new tool I just spent all day perfecting and releasing (it's totally nuts and replaces the need for scripts in a _lot_ of cases):

https://github.com/SteveJobzniak/mpv-tools/blob/master/multi-command-if.lua

🎉

**Comment by jonniek** [comment]
Thanks for the pull request. I'm having some problems with the basename though.
the script uses `io.popen('basename '..search..'/* | sed "s/^\\*$//"')` and produced a command like this:
`basename /home/anon/Pictures/dump//* | sed "s/^\*$//"`
which outputs
`basename: extra operand ‘/home/anon/Pictures/dump//1355837938164-w2x.jpg’`
And doesn't show any resulting files or folders. I tried fiddling with it but can't seem to understand how to output files.


All keys can be overridden in input.conf even if they aren't nil in the lua. Even keys that are not yet registered by the script(dynamic).

**Comment by ghost** [comment]
@donmaiq Ahh then you have found a difference in Linux basename vs Mac basename. On Mac, basename takes unlimited parameters and outputs them all without their paths. Since you are seeing "extra operand" I am guessing the Linux one refuses multiple files... Damn all these cross-platform differences in standard utilities!

Well, I just had a great idea of how to do this without spawning basename or find or any other utilities that may not work the same on every platform. Let me work on it and update the pull request in a moment. :)

Edit: Oh and yes you are right about keys being overridable in input.conf. The problem was that the way you were registering the keys took precedence over built-in default mpv keys, so "fullscreen" (f) was overwritten by navigator. That is why I added the ability to set the main "open navigator" key to nil. And the other important key is the "favorite list" key, which should only be bound while the navigator is open, so instead of permanently binding that in input.conf I made that one bindable in the settings area too. Those two are the primary keys to rebind (the rest are just logical arrow keys and backspace, with dynamic binding), which is why I singled those out for the settings object.

**Comment by ghost** [comment]
I have an idea now that will not just solve this. It will also **add** a feature that makes navigation much better. And even better at handling folders with lots of files. :) No globbing will be needed anymore.

**Comment by ghost** [comment]
@donmaiq Hey, it took a few hours since I was busy doing other things as well.

Here we go. A ton of **fun** enhancements, and an even faster cross-platform way of scanning for files.

- Enhanced method of scanning for file lists in folders, which now supports
  folders of any size (no more file globbing, so no more file count limit), and
  it's also much, much faster than the old method since we no longer call any
  complicated external programs (which used to do complex string processing).
- File lists are now sorted case-insensitively. The previous method placed all
  files with capital letters first, in a separate group, which made no sense.
- **Folders now all end with a "/" in the file listing, making it super easy to
  see which entries are files and which entries are folders!**
- Even safer way of escaping paths when we call external commands. Now properly
  escapes using double quotes. The old method would have broken if files had
  a ' or " in them. The new method is safe against ANY filename you can imagine.
- Made parentdir() safe against missing folders. If the folder to check the
  parent for doesn't exist, then it simply returns a "/" now, to return to the
  root instead of (absurdly) going to the parent dir of mpv's working dir.
- All calls to external functions are now totally robust, and fail gracefully if
  they lack the necessary filesystem permissions to visit particular folders.
- Silenced all external commands that printed stderr messages to console.
- Simplified the ignore-patterns list format. It is now just a string list.
- Massively increased the speed of the ignore-patterns searching, by only
  checking for a single match (via string.find) instead of doing a slow, global
  find-and-replace and string copying (which is what string.gsub did). And we
  now abort the scanning for more ignore-patterns as soon as one matches!

This is a **big** one!

Please let me know how it works on your system. :octocat:

**Comment by ghost** [comment]
Oh and whenever you merge this, you will have to edit outdated info in README.md regarding some of these new changes that affect it (such as now having macOS support, and we no longer rely on the slow "find", etc). And if you want to add a note about my big contribution, then a link back to my Github profile's [mpv-tools repository](https://github.com/SteveJobzniak/mpv-tools) to recommend my mpv scripts would be appreciated. I just want to help my fellow humans out, and there are some good, new tools in there that people have started to enjoy.

;-)

**Comment by jonniek** [comment]
Great it works very well! Thanks for the contribution. I will definitely credit you in the readme.

**Comment by ghost** [comment]
@donmaiq Fantastic, happy to hear it works on Linux! 👍 Thanks for everything and have a wonderful Christmas!

**Pull request merged**
